In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import scipy.stats as stats
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
pd.set_option('display.max_columns', None)

c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv('data2.csv')
df['new_target'] = df['Cholesterol Total (mg/dL)'].apply(
    lambda x: 1 if x == 187 else 0)
df.set_index('Responden', inplace=True)
df.drop('Cholesterol Total (mg/dL)', axis=1, inplace=True)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data2.csv'

In [ ]:
# encoding Jenis Kelamin if M = 1 and F = 0

df["Jenis Kelamin"] = df["Jenis Kelamin"].apply(lambda x: 1 if x == 'M' else 0)

# drop Tempat lahir
df.drop('Tempat lahir', axis=1, inplace=True)
df.head()

,Jenis Kelamin,Usia,Tekanan darah (S),Tekanan darah (D),Tinggi badan (cm),Berat badan (kg),IMT (kg/m2),Lingkar perut (cm),Glukosa Puasa (mg/dL),Trigliserida (mg/dL),Fat,Visceral Fat,Masa Kerja,new_target
Responden,,,,,,,,,,,,,,
1,1,19.0,126.0,88.0,172.5,49.5,16.53,66.0,84.0,99.0,26.4,6.0,0.97,1
2,1,19.0,120.0,80.0,158.0,53.6,21.50,71.0,84.0,99.0,26.4,6.0,0.60,1
3,1,19.0,120.0,80.0,170.0,59.5,20.59,80.0,80.0,99.0,26.4,6.0,1.37,1
4,0,19.0,100.0,70.0,149.0,45.1,20.31,62.0,81.0,99.0,30.5,3.5,1.00,1
5,1,19.0,110.0,70.0,171.6,62.4,21.19,78.0,84.0,99.0,26.4,6.0,4.00,1

In [ ]:
df = pd.read_csv('data2.csv')
df['new_target'] = df['Cholesterol Total (mg/dL)'].apply(
    lambda x: 1 if x == 187 else 0)
df.set_index('Responden', inplace=True)
df.drop(df[df['new_target'] == 1].index, inplace=True)
df.drop('new_target', axis=1, inplace=True)
df.head()

,Jenis Kelamin,Usia,Tekanan darah (S),Tekanan darah (D),Tinggi badan (cm),Berat badan (kg),IMT (kg/m2),Lingkar perut (cm),Glukosa Puasa (mg/dL),Cholesterol Total (mg/dL),Trigliserida (mg/dL),Fat,Visceral Fat,Masa Kerja,Tempat lahir
Responden,,,,,,,,,,,,,,,
10,M,20.0,120.0,80.0,179.0,80.95,25.26,90.0,80.0,170.0,89.0,26.4,6.0,2.0,Bandung
49,F,22.0,120.0,80.0,163.0,51.35,19.32,68.0,84.0,247.0,89.0,29.8,2.0,0.0,Surabaya
53,F,22.0,90.0,70.0,155.5,50.70,21.00,65.0,84.0,171.0,53.0,26.4,6.0,0.0,Jakarta
55,F,22.0,100.0,60.0,150.0,42.40,18.84,64.0,84.0,144.0,61.0,31.1,2.0,0.0,Surabaya
109,F,23.0,110.0,70.0,166.0,56.60,20.54,74.0,84.0,256.0,147.0,26.4,6.0,9.0,Purworejo

In [ ]:
# encoding Jenis Kelamin if M = 1 and F = 0

df["Jenis Kelamin"] = df["Jenis Kelamin"].apply(lambda x: 1 if x == 'M' else 0)

# drop Tempat lahir
df.drop('Tempat lahir', axis=1, inplace=True)
df.head()

,Jenis Kelamin,Usia,Tekanan darah (S),Tekanan darah (D),Tinggi badan (cm),Berat badan (kg),IMT (kg/m2),Lingkar perut (cm),Glukosa Puasa (mg/dL),Cholesterol Total (mg/dL),Trigliserida (mg/dL),Fat,Visceral Fat,Masa Kerja
Responden,,,,,,,,,,,,,,
10,1,20.0,120.0,80.0,179.0,80.95,25.26,90.0,80.0,170.0,89.0,26.4,6.0,2.0
49,0,22.0,120.0,80.0,163.0,51.35,19.32,68.0,84.0,247.0,89.0,29.8,2.0,0.0
53,0,22.0,90.0,70.0,155.5,50.70,21.00,65.0,84.0,171.0,53.0,26.4,6.0,0.0
55,0,22.0,100.0,60.0,150.0,42.40,18.84,64.0,84.0,144.0,61.0,31.1,2.0,0.0
109,0,23.0,110.0,70.0,166.0,56.60,20.54,74.0,84.0,256.0,147.0,26.4,6.0,9.0

In [ ]:
# Separate target variable and features
y = df['Cholesterol Total (mg/dL)']
X = df.drop('Cholesterol Total (mg/dL)', axis=1)

# Define the number of folds for cross-validation
num_folds = 50

# Initialize KFold with stratified sampling
kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)

# Initialize models
models = {
    'XGBoost': XGBRegressor(),
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(),
    'Lasso Regression': Lasso(),
    'Random Forest': RandomForestRegressor()
}

# Function to perform k-fold cross-validation


def perform_cross_validation(model, X, y, kf):
    # Initialize list to store RMSE scores for each fold
    rmse_scores = []

    # Perform k-fold cross-validation
    for train_index, test_index in kf.split(X, y):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        # Train the model
        model.fit(X_train, y_train)

        # Make predictions on the test set
        y_pred = model.predict(X_test)

        # Calculate RMSE
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))

        # Append RMSE to the list of scores
        rmse_scores.append(rmse)

    return rmse_scores


# Perform cross-validation for each model
results = {}
for model_name, model in models.items():
    rmse_scores = perform_cross_validation(model, X, y, kf)
    average_rmse = np.mean(rmse_scores)
    results[model_name] = {'RMSE Scores': rmse_scores,
                           'Average RMSE': average_rmse}

# Print the results for each model
for model_name, result in results.items():
    print(model_name + ":")
    print("RMSE Scores:", result['RMSE Scores'])
    print("Average RMSE:", result['Average RMSE'])
    print()

XGBoost:
RMSE Scores: [39.315672705719784, 32.811208598467395, 27.675194313699265, 31.217114313439012, 28.15370230450946, 29.659513710053073, 27.60034620233516, 17.288227626677074, 25.920561753028892, 34.22653992226646, 29.40671162576366, 30.217309444967277, 40.140574634794454, 28.961680488344957, 30.242891403736653, 33.548843199744304, 26.455177819448593, 29.879771967731067, 19.65238027933191, 32.99061563129711, 35.52929184881141, 29.418637916150423, 33.99722046119756, 48.43649239036248, 23.24618460267005, 25.346558351526177, 45.16490827114098, 30.769025410211103, 30.856368345964263, 36.05356727974804, 30.746813143902582, 31.513796727515178, 25.172657720788116, 41.71176260668349, 26.08018023061633, 35.79341938262247, 37.1064067364235, 43.88856088704848, 43.324273415647454, 22.01378923047906, 30.682942144189067, 25.82784259050383, 40.6573262958665, 28.769829373561123, 37.14275581823589, 29.704273474411725, 36.235528506975704, 42.336840255626996, 34.062695386913646, 24.161221153785366]
Average RMSE: 32.02230415809869

Linear Regression:
RMSE Scores: [39.21527231323727, 36.28872941084489, 28.369441199878676, 33.59274810748177, 31.74210976591943, 35.52601735039904, 27.132123488859744, 14.585293951110517, 26.408412401176616, 28.782469088344126, 23.482335728326845, 21.658331353028885, 44.20268921901703, 16.018017876369225, 23.514627475102753, 23.15109550088483, 29.453530345957876, 33.44094005318766, 26.492327739037744, 26.6023875402011, 32.781781202980966, 29.784226585531638, 30.042746862825222, 61.742538969535154, 16.05355634345852, 16.923128977923213, 36.33342771835173, 49.36214254210971, 32.19513218818777, 35.905983803507965, 31.727041434133795, 31.358564698702587, 33.79429901458017, 43.28546319111993, 22.048571855162017, 28.77962126469336, 29.175248306848072, 43.81674757793073, 32.22168746075832, 18.12500190345489, 25.90113595119252, 21.463694455187042, 34.712970824253, 30.619297941363122, 28.912134513725295, 25.15567041134048, 37.15172367135008, 41.42637629253104, 40.695220684658956, 27.961234273543596]
Average RMSE: 30.78230541658614

Ridge Regression:
RMSE Scores: [39.275982962412456, 36.22424978480864, 28.35288772119971, 33.581816710429415, 31.774062385897388, 35.546146647911854, 27.21619369292332, 14.61830417344464, 26.345142987962117, 28.81343854945013, 23.484743657679566, 21.707516013685122, 44.18144253719597, 16.02063260390954, 23.514096715066415, 23.08396414062852, 29.397487309078667, 33.40917861199936, 26.526783987341762, 26.61248106701983, 32.76464514188998, 29.727800155159386, 30.058816545367538, 61.68902858980901, 16.073003876849555, 16.964946528583248, 36.32400168687208, 49.342219288801104, 32.26806368295617, 35.902208060077356, 31.78906201868614, 31.35708689260912, 33.76940676356295, 43.24324632545732, 22.08043779685423, 28.764903427704713, 29.25203031692565, 43.76081485030514, 32.23237867389687, 18.167783256970367, 25.848990667941845, 21.467827293104133, 34.705542714176985, 30.61454621962499, 28.919822757347056, 25.167749836532572, 37.16641995538197, 41.37133496400963, 40.66176034406444, 27.983637655707557]
Average RMSE: 30.782521370945474

Lasso Regression:
RMSE Scores: [41.36405821598021, 34.52500438047272, 27.57809238916651, 33.37651686478142, 32.30344877841442, 36.60043665816172, 30.188086509254322, 15.923993384771334, 25.046866347773037, 29.445186269769593, 23.989541412511088, 23.31573760756068, 43.83476900153703, 16.196413987318614, 23.593063844640646, 21.581577680828747, 28.022543601649847, 32.29745186003254, 27.805272885828717, 26.653567526382755, 32.7988171329715, 28.40781022485077, 30.586528979942177, 59.73570532421074, 16.82382508094713, 18.314671776367256, 36.30724964954421, 48.00132416669167, 34.76235064994586, 35.45251431420483, 34.09237780509059, 31.299041156303733, 32.95160447499792, 41.857287959960395, 22.79847671307599, 28.477228068223756, 31.945826639090967, 42.57740020740134, 32.778747477039055, 19.659676258914345, 25.10693792154645, 21.90794410513717, 34.23239616352639, 30.45240466530978, 29.695590591965157, 26.130018904179686, 37.93298978424393, 40.18964834617164, 39.24388690733327, 28.562007475574834]
Average RMSE: 30.934478362631967

Random Forest:
RMSE Scores: [41.064567673139074, 32.47706001584391, 27.055764803289325, 32.74776133917054, 31.54529312245835, 33.606793009206285, 33.42551379900199, 19.594733522510122, 25.400705251483217, 28.74969438572743, 25.31140328712805, 25.33138262027056, 41.99597545652981, 20.318011042601405, 26.23406945176444, 26.89493480530894, 26.903445200129365, 30.49992533522903, 22.66030871168994, 31.891599207314773, 34.55734982999604, 27.71555011508554, 28.988041578303537, 44.81519121499275, 23.81050646630219, 13.466119100778949, 40.217936523171076, 33.92110713244645, 33.17283609439287, 30.809819568088702, 28.248469467791125, 32.28210100743979, 30.00502745753239, 43.80108778225822, 25.271459108143027, 30.057307385604705, 32.15840297368919, 38.74976340103722, 38.35526075094168, 19.18423358338347, 25.071704986081244, 22.990622594282375, 34.33521476163026, 34.346033779224584, 33.266561289078254, 29.43634704362495, 34.534909347446735, 41.47931543662345, 28.454204674113875, 26.030923149208522]
Average RMSE: 30.464846992849793